// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrmesipxvejvtmfklntf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZybWVzaXB4dmVqdnRtZmtsbnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjA2ODMsImV4cCI6MjA1ODIzNjY4M30.7Ktdiqpeaewd33WGbhHPkuCyym3uMoMVLpS_DPtnFUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);